[package]
name = "godot"
version = "0.1.0"
edition = "2021"
rust-version = "1.78"
license = "MPL-2.0"
keywords = ["gamedev", "godot", "engine", "2d", "3d"] # possibly: "ffi"
categories = ["game-engines", "graphics"]

[features]
default = ["codegen-full"]
api-4-0 = ["godot-core/api-4-0"]
api-4-1 = ["godot-core/api-4-1"]
api-custom = ["godot-core/api-custom"]
custom-godot = ["api-custom"]
double-precision = ["godot-core/double-precision"]
experimental-godot-api = ["godot-core/experimental-godot-api"]
experimental-threads = ["godot-core/experimental-threads"]
experimental-wasm = []
formatted = ["godot-core/codegen-fmt"]
lazy-function-tables = ["godot-core/codegen-lazy-fptrs"]
serde = []

# Private features, they are under no stability guarantee
codegen-full = ["godot-core/codegen-full"]
debug-log = ["godot-core/debug-log"]
trace = ["godot-core/trace"]

[dependencies]
godot-core = { path = "../godot-core" }
godot-macros = { path = "../godot-macros" }

# https://docs.rs/about/metadata
[package.metadata.docs.rs]
features = ["experimental-godot-api"]
rustdoc-args = ["--cfg", "published_docs"]
