[package]
name = "godot-core"
version = "0.1.0"
edition = "2021"
rust-version = "1.78"
license = "MPL-2.0"
keywords = ["gamedev", "godot", "engine", "2d", "3d"] # possibly: "ffi"
categories = ["game-engines", "graphics"]

[features]
default = []
codegen-fmt = ["godot-ffi/codegen-fmt", "godot-codegen/codegen-fmt"]
codegen-full = ["godot-codegen/codegen-full"]
codegen-lazy-fptrs = [
    "godot-ffi/codegen-lazy-fptrs",
    "godot-codegen/codegen-lazy-fptrs",
]
api-custom = ["godot-ffi/api-custom", "godot-codegen/api-custom"]
double-precision = ["godot-codegen/double-precision"]
experimental-godot-api = ["godot-codegen/experimental-godot-api"]
experimental-threads = ["godot-ffi/experimental-threads"]
debug-log = ["godot-ffi/debug-log"]
trace = []
api-4-0 = ["godot-ffi/api-4-0"]
api-4-1 = ["godot-ffi/api-4-1"]

[dependencies]
godot-ffi = { path = "../godot-ffi" }

# See https://docs.rs/glam/latest/glam/index.html#feature-gates
glam = { version = "0.27", features = ["debug-glam-assert"] }
serde = { version = "1", features = ["derive"]}
godot-cell = { path = "../godot-cell" }
anyhow = "1.0.83"
serde_json = "1.0.117"

# Reverse dev dependencies so doctests can use `godot::` prefix
[dev-dependencies]
godot = { path = "../godot" }
serde_json = { version = "1.0" }

[build-dependencies]
godot-bindings = { path = "../godot-bindings" }
godot-codegen = { path = "../godot-codegen" }

# https://docs.rs/about/metadata
[package.metadata.docs.rs]
features = ["experimental-godot-api"]
rustdoc-args = ["--cfg", "published_docs"]
